---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/houses":
    get:
      summary: index of houses
      responses:
        '200':
          description: successful
    post:
      summary: create house
      parameters: []
      responses:
        '201':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  icon:
                    type: string
                  house_name:
                    type: string
                  city:
                    type: string
                  description:
                    type: string
                  bedrooms:
                    type: integer
                  bathrooms:
                    type: integer
                  rent:
                    type: integer
                  security_deposit:
                    type: integer
                  contact_phone_number:
                    type: string
                  admin_user_id:
                    type: integer
                required:
                - icon
                - house_name
                - city
                - description
                - bedrooms
                - bathrooms
                - rent
                - security_deposit
                - contact_phone_number
                - admin_user_id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                icon:
                  type: string
                house_name:
                  type: string
                city:
                  type: string
                description:
                  type: string
                bedrooms:
                  type: integer
                bathrooms:
                  type: integer
                rent:
                  type: integer
                security_deposit:
                  type: integer
                contact_phone_number:
                  type: string
                admin_user_id:
                  type: integer
  "/api/v1/houses/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    delete:
      summary: Deactivate house
      responses:
        '200':
          description: successful
  "/api/v1/reservations":
    get:
      summary: list reservations
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
    post:
      summary: create reservation
      parameters: []
      responses:
        '201':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  date:
                    type: date
                  user_id:
                    type: integer
                  room_id:
                    type: integer
                  city_id:
                    type: integer
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                required:
                - city_id
                - room_id
                - date
                - user_id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                city_id:
                  type: integer
                room_id:
                  type: integer
                user_id:
                  type: integer
              required:
              - city_id
              - room_id
              - date
              - user_id
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
